registrationapp/urls.py
from django.urls import path
from .views import main, dataView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', main, name='regdoc'),
    path("data/", dataView, name='data'),

]

sapp/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', index, name="index"),
    path('about-us/', about_us_view, name="about_url"),
    path('admission-rules/', admission_rules, name="admission_rules"),
    path('code-of-honor/', code_of_honor, name="code_of_honor_url"),
    path('login/', CollegeLoginView.as_view(), name="login"),
    path('register/', CollegeRegisterView.as_view(), name="register"),
    path('logout/', CollegeLogoutView.as_view(), name="logout"),
    path('appeal-send/', appealView, name='appealRoute')
]

silkwaycollege/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18/', include('django.conf.urls.i18n')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('req/', include('registrationapp.urls'))
]

urlpatterns += i18n_patterns(
    path('', include(('sapp.urls', 'sapp'))),
    path('employees/', include(('employeesapp.urls', 'employeesapp'))),
    path('speciliazation/', include(('specializationapp.urls', 'specapp'))),
    path('news/', include(('newsapp.urls', 'newsapp'))),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registrationapp/models.py
from django.db import models
from docxtpl import DocxTemplate
from django.conf import settings
from specializationapp.models import Specialization

class EduProgram(models.Model):
    name = models.CharField('Образовательная программа', max_length=255)

    class Meta:
        verbose_name = "Образовательную программу"
        verbose_name_plural = "Образовательные программы"

    def __str__(self):
        return self.name

class App(models.Model):

    lang = (
        ('Русский', 'Русский'),
        ('Казахский', 'Казахский'),
    )
    gend = (
        ('Мужчина', 'Мужчина'),
        ('Женщина', 'Женщина'),
    )

    poloj = (
        ('Ниже среднего', 'Ниже среднего'),
        ('Среднее', 'Среднее'),
        ('Высокое', 'Высокое'),
    )

    surname = models.CharField('Фамилия', max_length=255)
    name = models.CharField('Имя', max_length=255)
    otch = models.CharField('Отчество', max_length=255, null=True, blank=True, default="")
    phone = models.CharField('Номер телефона', max_length=11)
    edu_program = models.ForeignKey(Specialization, on_delete=models.CASCADE, verbose_name='Образовательная программа')
    language = models.CharField('Язык обучения', choices=lang, max_length=255)
    finish_edu = models.TextField("Прежнее место обучение и дата окончания", null=True, blank=True)
    address = models.CharField("Адрес проживания", max_length=255)
    place = models.BooleanField("Общежитие" ,default=False)
    about = models.TextField("Информация о себе", null=True, blank=True)
    gender = models.CharField("Пол", choices=gend, max_length=255)
    birthday = models.DateField("Дата рождения",auto_now_add=False, blank=True, null=True)
    born_place = models.CharField("Место рождения", max_length=255)
    national = models.CharField("Нация", max_length=255)
    polojenie = models.CharField("Материальное положение", max_length=255, choices=poloj)
    information_parent_mom = models.TextField("ФИО матери, место проживания, номер телефона", null=True, blank=True)
    information_parent_dad = models.TextField("ФИО отца, место проживания, номер телефона", null=True, blank=True)
    created_at = models.DateField(auto_now_add=False, null=True, blank=True)

    id_card_front = models.FileField('Уд.лич лицевая', upload_to='id_card/', null=True, blank=True)
    id_card_back = models.FileField('Уд.лич обратная', upload_to='id_card/', null=True, blank=True)
    diplom = models.FileField('Диплом', upload_to='diplom/')
    zayavka = models.FileField('Заявка для приема на учебу', upload_to='zayavka/')
    fluro = models.FileField("075-y(флюрография)", upload_to="fluro/")
    zdorovie = models.FileField("063-y(Паспорт о здоровье)", upload_to="zdorovie/")
    photo = models.FileField("3x4 фото", upload_to="photo/")
    genereted_file = models.FileField(upload_to="genereted/", null=True, blank=True)


    def __str__(self):
        return f'{self.surname} {self.name}'

    def save(self, *args, **kwargs):
        doc = DocxTemplate("template_form.docx")
        if self.place:
            place = "Керек"
        else:
            place = "Керек емес"
        context = {
            'fio': f'{self.surname} {self.name} {self.otch}',
            'finish_edu': self.finish_edu,
            'address': self.address,
            'place': place,
            'edu': self.edu_program,
            'about_me': self.about,
            'gender': self.gender,
            'birthday': self.birthday,
            'born_place': self.born_place,
            'national': self.national,
            'pol': self.polojenie,
            'inf_mom': self.information_parent_mom,
            'inf_dad': self.information_parent_dad,
            'about': self.about,
            'created': self.created_at
        }
        doc.render(context)
        name = f"/genereted/{self.name}_{self.surname}_request.docx"
        print(settings.MEDIA_ROOT)
        doc.save(str(settings.MEDIA_ROOT)+name)
        self.genereted_file = name
        super(App, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Заявку"
        verbose_name_plural = "Заявки"

# # окуга кабылдау туралы отиниш
# # билим туралы кужат
# # 075-у нысаны бойынша медициналык аныктама(флюрография)
# # 063-у нысаны бойынша медициналык (денсаулык паспорты)
# # туу туралы куалигин немесе жеке куалигинин коширмеси
# 3х4 фото

registrationapp/forms.py
from django import forms
from .models import App
from specializationapp.models import Specialization

lang = (
        ('Русский', 'Русский'),
        ('Казахский', 'Казахский'),
    )

gend = (
        ('Мужчина', 'Мужчина'),
        ('Женщина', 'Женщина'),
    )

poloj = (
        ('Ниже среднего', 'Ниже среднего'),
        ('Среднее', 'Среднее'),
        ('Высокое', 'Высокое'),
    )
class AppForm(forms.ModelForm):
    edu_program = forms.ModelChoiceField(queryset=Specialization.objects.all(), to_field_name="id",widget=forms.Select(attrs={'class': 'custom-select'}) )
    language = forms.ChoiceField(choices=lang, widget=forms.Select(attrs={'class': 'custom-select'}))
    gender = forms.ChoiceField(choices=gend, widget=forms.Select(attrs={'class': 'custom-select'}))
    polojenie = forms.ChoiceField(choices=poloj, widget=forms.Select(attrs={'class': 'custom-select'}))
    class Meta:
        model = App
        fields = '__all__'
        widgets = {
            'surname': forms.TextInput(attrs={'class': 'form-control', "placeholder": "Ваше фамилия"}),
            'name': forms.TextInput(attrs={'class': 'form-control', "placeholder": "Ваше имя"}),
            'otch': forms.TextInput(attrs={'class': 'form-control', "placeholder": "Ваше отчество"}),
            'phone': forms.TextInput(attrs={'class': 'form-control', "placeholder": " +7"}),
            'finish_edu': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'place': forms.CheckboxInput(attrs={'class': 'custom-checkbox'}),
            'about': forms.TextInput(attrs={'class': 'form-control'}),
            'birthday': forms.DateInput(attrs={'type':"date", 'class':"icon-date_range"}),
            'born_place': forms.TextInput(attrs={'class': 'form-control'}),
            'national': forms.TextInput(attrs={'class': 'form-control'}),
            'information_parent_mom': forms.Textarea(attrs={'class': 'form-control'}),
            'information_parent_dad': forms.Textarea(attrs={'class': 'form-control'}),
            'created_at': forms.DateInput(attrs={'type':"datetime-local", 'class':"icon-date_range"}),
            'id_card_front': forms.FileInput(attrs={'class': 'custom-file-input', "onChange":"updateValue(this, 'id_card_frontLabel')"}),
            'id_card_back': forms.FileInput(attrs={'class': 'custom-file-input', "placeholder": "Уд.лич обратная", "onChange":"updateValue(this, 'id_card_backLabel')"}),
            'diplom': forms.FileInput(attrs={'class': 'custom-file-input', "placeholder": "Диплом", "onChange":"updateValue(this, 'diplomLabel')"}),
            'zayavka': forms.FileInput(attrs={'class': 'custom-file-input', "placeholder": "Заявление на обучение", "onChange":"updateValue(this, 'zayavkaLabel')"}),
            'fluro': forms.FileInput(attrs={'class': 'custom-file-input', "placeholder": "Флюрография", "onChange":"updateValue(this, 'fluroLabel')"}),
            'zdorovie': forms.FileInput(attrs={'class': 'custom-file-input', "placeholder": "Справка о здоровье", "onChange":"updateValue(this, 'zdorovieLabel')"}),
            'photo': forms.FileInput(attrs={'class': 'custom-file-input', "placeholder": "3х4 фото", "onChange":"updateValue(this, '34photoSize')"}),
        }
        # finish_edu = models.TextField
        # address = models.CharField
        # place = models.BooleanField
        # about = models.TextField
        # gender = models.CharField
        # birthday = models.DateField
        # born_place = models.CharField
        # national = models.CharField
        # polojenie = models.CharField
        # information_parent_mom = models.TextField
        # information_parent_dad = models.TextField
        # created_at = models.DateField

registrationapp/views.py
from django.shortcuts import render, redirect
from .forms import AppForm
from django.contrib import messages
from .models import App,EduProgram
def main(request):

    form = AppForm()
    content = {
        "form": form
    }
    return render(request, 'registrationTemplate/main.html', content)

def dataView(request):
    if request.method == 'POST':
        form = AppForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Файлы были успешно загружены')
            return redirect('/req/')
        else:
            print(form)
            print(form.errors)
            messages.error(request, 'Форма неверно заполнена ')
            return redirect('/req/')

    return render(request, 'registrationTemplate/main.html')

registrationapp/templates/registrationTemplate/main.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700,900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'registrationapp/fonts/icomoon/style.css' %}">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'registrationapp/css/bootstrap.min.css' %}">

    <!-- Style -->
    <link rel="stylesheet" href="{% static 'registrationapp/css/style.css' %}">

    <title>Contact Form #7</title>
    <style>
      .col-form-label{
        color:#35467d;
      }
    </style>
  </head>
  <body>


  <div class="content">

    <div class="container">
      <div class="row align-items-stretch no-gutters contact-wrap">
        <div class="col-md-8">
          <div class="form h-100">


            <h3>Колледжге түсуге өтінім нысаны</h3>
            <form action="{% url 'data' %}" class="mb-5" method="POST" id="" name="contactForm" enctype="multipart/form-data">
                {% csrf_token %}
            <div class="row">
                   {% if messages %}
                      {% for msg in messages %}
                        <div class="alert alert-info alert-dismissable">
                            <a style="text-decoration: none" href="{% url 'regdoc' %}"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button></a>
                          {{msg.message}}
                        </div>
                      {% endfor %}
                  {% endif %}
              </div>
              <div class="row">
                <div class="col-md-6 form-group mb-5">
                  <label for="id_name" class="col-form-label">Аты:</label>
                  {{ form.name }}
                </div>
                <div class="col-md-6 form-group mb-5">
                  <label for="id_surname" class="col-form-label">Тегі:</label>
                  {{ form.surname }}
                </div>
              </div>

              <div class="row">
                <div class="col-md-6 form-group mb-5">
                  <label for="id_otch" class="col-form-label">Әкесінің аты:</label>
                  {{ form.otch }}
                </div>
                <div class="col-md-6 form-group mb-5">
                  <label for="id_phone" class="col-form-label">Телефон</label>
                  {{ form.phone }}
                </div>
                  <div class="col-md-6 form-group mb-5">
                  <label for="id_finish_edu" class="col-form-label"> (мектеп немесе басқа оқу орнының атауы, қай жылы бітіргенін жазу)</label>
                  {{ form.finish_edu }}
                </div>
                  <div class="col-md-6 form-group mb-5">
                  <label for="id_address" class="col-form-label">Тұрғынның адресі:</label>
                  {{ form.address }}
                </div>
                  <div class="col-md-6 form-group mb-5">
                  <label for="id_place" class="col-form-label form-check-label">Жатақхана қажет, қажет емес (сызып көрсетіңіз):</label>
                      {{ form.place }}
                </div>
                  <div class="col-md-6 form-group mb-5">
                  <label for="id_about" class="col-form-label">Өзім жайлы мәлімет: </label>
                      {{ form.about }}
                </div>
                  <div class="col-md-6 form-group mb-5">
                  <label for="id_birthday" class="col-form-label">Туған жылы: </label>
                      {{ form.birthday }}
                </div>
                  <div class="col-md-6 form-group mb-5">
                  <label for="id_born_place" class="col-form-label">Туған  жері: </label>
                      {{ form.born_place }}
                  </div>
                  <div class="col-12 ">
                    <h3>Ата-анасының аты-жөні,  мекен – жайы, атқаратын қызметі, жұмыс орнының атауы байланыс телефондары:</h3>
                  </div>
                  <div class="col-md-6 form-group mb-5">
                      <label for="id_information_parent_mom" class="col-form-label">Шешесі:</label>
                      {{ form.information_parent_mom }}
                  </div>
                  <div class="col-md-6 form-group mb-5">
                      <label for="id_information_parent_dad" class="col-form-label">Әкесі: </label>
                      {{ form.information_parent_dad }}
                  </div>
                  <div class="col-md-6 form-group mb-5">
                      <label for="id_polojenie" class="col-form-label">Әлеуметтік жағдайы:</label>
                      {{ form.polojenie }}
                  </div>
                  <div class="col-md-6 form-group mb-5">
                      <label for="id_gender" class="col-form-label">Жынысы: </label>
                      {{ form.gender }}
                  </div>
                  <div class="col-md-6 form-group mb-5">
                      <label for="id_national" class="col-form-label">Ұлты: </label>
                      {{ form.national }}
                  </div>
                  <div class="col-md-6 form-group mb-5">
                    <label for="id_national" id="id_edu_program" class="col-form-label">Мамандық бойынша: </label>
                    {{form.edu_program}}
                  </div>
                  <div class="col-md-6 form-group mb-5">
                    <label for="id_national" id="id_edu_program" class="col-form-label">Тілі:</label>
                    {{ form.language }}
                  </div>
                
        
              <div class="row ">
                <div class="col-md-6 form-group">
                  <label for="" id="id_card_frontLabel" class="custom-file-label">{{  form.id_card_front.label }}</label>
                  {{ form.id_card_front }}
                </div>
                <div class="col-md-6 form-group mb-5">
                  <label for="" id="id_card_backLabel" class="custom-file-label">{{ form.id_card_back.label }}</label>
                  {{ form.id_card_back }}
                </div>
              </div>

              <div class="row">
                <div class="col-md-6 form-group mb-5">
                  <label for="" id="diplomLabel" class="custom-file-label">{{ form.diplom.label }}</label>
                  {{ form.diplom }}
                </div>
                  <div class="col-md-6 form-group mb-5">
                  <label for="" id="zayavkaLabel" class="custom-file-label">{{ form.zayavka.label }}</label>
                  {{ form.zayavka }}
                </div>
              </div>
                <div class="row">
                <div class="col-md-6 form-group mb-5">
                  <label for="" id="fluroLabel" class="custom-file-label">{{ form.fluro.label }}</label>
                  {{ form.fluro }}
                </div>
                  <div class="col-md-6 form-group mb-5">
                  <label for="" id="zdorovieLabel" class="custom-file-label">{{ form.zdorovie.label }}</label>
                  {{ form.zdorovie }}
                </div>
                    <div class="col-md-12 form-group mb-5">
                  <label for="" id="34photoSize" class="custom-file-label">{{ form.photo.label }}</label>
                  {{ form.photo }}
                </div>
              </div>
              <div class="row">
                <div class="col-md-12 form-group">
                  <input type="submit" value="Отправить" class="btn btn-primary rounded-0 py-2 px-4" style="background-color: #8f2437">
                  <span class="submitting"></span>
                </div>
              </div>
            </form>

            <div id="form-message-warning mt-4"></div>
            <div id="form-message-success">
              Your message was sent, thank you!
            </div>

          </div>
        </div>
      </div>
        <div class="col-md-4">
          <div class="contact-info h-100">
            <h3>Контактная информация</h3>
              <a style="text-decoration: none; color:white" href="/"><p class="mb-5">Высший педагогический колледж Shymkent</p></a>
            <ul class="list-unstyled">
              <li class="d-flex">
                <span class="wrap-icon icon-room mr-3"></span>
                <span class="text">г.Шымкент, ул. 8 марта, 22</span>
              </li>
              <li class="d-flex">
                <span class="wrap-icon icon-phone mr-3"></span>
                <span class="text">+7 7252 506136</span>
              </li>
              <li class="d-flex">
                <span class="wrap-icon icon-envelope mr-3"></span>
                <span class="text">ukpk_shym@mail.ru</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

  </div>



      <script>
        const updateValue = (event, id) => {
          console.log(id)
            let elem = document.getElementById(`${id}`);
            console.log(elem)
            elem.innerHTML = event.value
        }
      </script>

  </body>
</html>